import type { Express, Request, Response } from "express";
import { db, createSession, getUserBySession, upsertUser, savePlan, saveProgress, listProgress, saveReminder, listReminders, listNotifications, hashToken } from "./db";
const SESSION_COOKIE="fysiq_session", SESSION_MAX_AGE=60*60*24*30;
function cookie(req:Request){const h=req.headers.cookie||""; const p=h.split(";").map(v=>v.trim()).find(v=>v.startsWith(SESSION_COOKIE+"=")); return p?decodeURIComponent(p!.slice(SESSION_COOKIE.length+1)):undefined;}
function setCookie(res:Response,token:string){const secure=String(process.env.APP_URL||"").startsWith("https://")?"; Secure":"";res.setHeader("Set-Cookie",`${SESSION_COOKIE}=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${SESSION_MAX_AGE}${secure}`)}
function clearCookie(res:Response){res.setHeader("Set-Cookie",`${SESSION_COOKIE}=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0`)}
async function user(req:Request){return getUserBySession(cookie(req));}
async function verifyGoogle(credential:string){const clientId=String(process.env.GOOGLE_CLIENT_ID||"").trim();if(!clientId||!credential)throw new Error("Google OAuth n'est pas configuré.");const r=await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${encodeURIComponent(credential)}`);if(!r.ok)throw new Error("Jeton Google invalide ou expiré.");const t=await r.json() as Record<string,string>;if(t.aud!==clientId||t.email_verified!=="true"||(t.iss!=="https://accounts.google.com"&&t.iss!=="accounts.google.com")||!t.sub||!t.email)throw new Error("Identité Google invalide.");if(t.exp&&Number(t.exp)*1000<Date.now())throw new Error("Session Google expirée.");return{email:t.email.toLowerCase(),displayName:t.name||undefined,avatarUrl:t.picture||undefined,googleSub:t.sub};}
export function registerAuthRoutes(app:Express){
app.get("/api/auth/config",(_q,r)=>r.json({googleClientId:process.env.GOOGLE_CLIENT_ID||""}));
app.get("/api/auth/me",async(req,res)=>{try{const u=await user(req);return res.json(u?{authenticated:true,user:{id:u.id,email:u.email,displayName:u.display_name,avatarUrl:u.avatar_url}}:{authenticated:false})}catch(e){console.error(e);return res.status(500).json({authenticated:false})}});
app.post("/api/auth/google",async(req,res)=>{try{if(!db)return res.status(503).json({error:"Base de données indisponible"});const identity=await verifyGoogle(String(req.body?.credential||""));const u=await upsertUser(identity);if(!u)return res.status(503).json({error:"Création du compte impossible"});const s=await createSession(u.id);if(!s)return res.status(503).json({error:"Création de session impossible"});setCookie(res,s);return res.json({authenticated:true,user:{id:u.id,email:u.email,displayName:u.display_name,avatarUrl:u.avatar_url}})}catch(e){return res.status(401).json({error:e instanceof Error?e.message:"Connexion Google impossible"})}});
app.post("/api/auth/logout",async(req,res)=>{const t=cookie(req);if(t&&db)try{await db.query("DELETE FROM sessions WHERE token_hash=$1",[hashToken(t)])}catch(e){console.error(e)}clearCookie(res);return res.json({ok:true})});
app.post("/api/data/plan",async(req,res)=>{const u=await user(req);if(!u)return res.status(401).json({error:"Authentification requise"});const p=await savePlan(u.id,String(req.body?.tierId||"performance"),req.body?.plan||{});return p?res.json({plan:p}):res.status(503).json({error:"Base indisponible"})});
app.post("/api/data/progress",async(req,res)=>{const u=await user(req);if(!u)return res.status(401).json({error:"Authentification requise"});const p=await saveProgress(u.id,String(req.body?.workoutKey||""),req.body?.payload||{},req.body?.completedAt);return p?res.json({progress:p}):res.status(503).json({error:"Base indisponible"})});
app.get("/api/data/progress",async(req,res)=>{const u=await user(req);if(!u)return res.status(401).json({error:"Authentification requise"});return res.json({progress:await listProgress(u.id)})});
app.post("/api/data/reminders",async(req,res)=>{const u=await user(req);if(!u)return res.status(401).json({error:"Authentification requise"});if(!req.body?.workoutId||!req.body?.scheduledAt)return res.status(400).json({error:"workoutId et scheduledAt sont requis"});const x=await saveReminder(u.id,{workoutId:String(req.body.workoutId),scheduledAt:String(req.body.scheduledAt),status:String(req.body.status||"pending")});return x?res.json({reminder:x}):res.status(503).json({error:"Base indisponible"})});
app.get("/api/data/reminders",async(req,res)=>{const u=await user(req);if(!u)return res.status(401).json({error:"Authentification requise"});return res.json({reminders:await listReminders(u.id)})});
app.get("/api/data/notifications",async(req,res)=>{const u=await user(req);if(!u)return res.status(401).json({error:"Authentification requise"});return res.json({notifications:await listNotifications(u.id)})});
}
// Persistence wiring workflow trigger marker.
