import React from "react";
import { TrainingPlan } from "../types";
import { Sparkles, Lock, ArrowRight, Eye, Music, Flame, Award, ShieldCheck, CheckCircle2 } from "lucide-react";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip } from "recharts";
import { Language } from "../utils/translator";

interface AhaPreviewStepProps {
  plan: TrainingPlan;
  onUnlockClick: () => void;
  language: Language;
}

export const AhaPreviewStep: React.FC<AhaPreviewStepProps> = ({
  plan,
  onUnlockClick,
  language
}) => {
  const isFr = language === "FR";

  // Chart data for 8-week predicted progress
  const progressChartData = [
    { week: isFr ? "S0 (Départ)" : "W0 (Start)", muscleIdx: 60, fatIdx: 22 },
    { week: "W2", muscleIdx: 65, fatIdx: 20 },
    { week: isFr ? "S4 (Bilan 1)" : "W4 (Check 1)", muscleIdx: 72, fatIdx: 17 },
    { week: "W6", muscleIdx: 80, fatIdx: 15 },
    { week: isFr ? "S8 (Objectif)" : "W8 (Target)", muscleIdx: 88, fatIdx: 13 }
  ];

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 space-y-8">
      {/* Aha Header */}
      <div className="text-center space-y-3">
        <div className="inline-flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/30 px-3.5 py-1.5 rounded-full text-xs font-bold text-emerald-400">
          <Sparkles className="w-4 h-4 animate-spin-slow" />
          <span>{isFr ? "Ton Plan Personnalisé Est Prêt !" : "Your Personalized Plan is Ready!"}</span>
        </div>
        <h2 className="text-3xl sm:text-5xl font-black uppercase tracking-tight font-display text-white">
          {plan.programTitle}
        </h2>
        <p className="text-gray-300 max-w-2xl mx-auto text-sm sm:text-base">
          {isFr
            ? "Voici l'aperçu de ton programme conçu par FysiqForge AI à partir de ton analyse photo et de tes réponses."
            : "Here is your plan preview generated by FysiqForge AI based on your photo scan and preferences."}
        </p>
      </div>

      {/* Grid of Impression: AI Photo Scan + Transformation Chart */}
      <div className="grid lg:grid-cols-12 gap-6">
        {/* Left: AI Morphological Report */}
        <div className="lg:col-span-6 bg-[#16161E] border border-white/10 rounded-3xl p-6 space-y-6 shadow-xl">
          <div className="flex items-center justify-between pb-3 border-b border-white/10">
            <span className="text-xs font-extrabold uppercase text-[#FF5500] tracking-wider flex items-center gap-1.5">
              <Eye className="w-4 h-4" /> Rapport d'Analyse Visuelle Photo
            </span>
            <span className="bg-[#FF5500]/20 text-[#FF5500] text-[10px] font-bold px-2 py-0.5 rounded border border-[#FF5500]/30">
              Score Symétrie : {plan.analysis.symmetryScore}/100
            </span>
          </div>

          <div className="space-y-4 text-sm">
            <div className="bg-[#121218] p-3.5 rounded-xl border border-white/5 space-y-1">
              <p className="text-xs text-gray-400 font-semibold uppercase">Morphologie Détectée</p>
              <p className="font-bold text-white">{plan.analysis.morphologyType}</p>
            </div>

            <div className="bg-[#121218] p-3.5 rounded-xl border border-white/5 space-y-1">
              <p className="text-xs text-gray-400 font-semibold uppercase">Estimation Taux de Gras Visuel</p>
              <p className="font-bold text-amber-400">{plan.analysis.estimatedBodyFat}</p>
            </div>

            <div className="space-y-2">
              <p className="text-xs text-gray-400 font-semibold uppercase">Zones Prioritaires Ciblées</p>
              <div className="flex flex-wrap gap-2">
                {plan.analysis.priorityZones.map((zone, idx) => (
                  <span
                    key={idx}
                    className="bg-[#FF5500]/15 text-[#FF5500] border border-[#FF5500]/30 px-2.5 py-1 rounded-lg text-xs font-bold"
                  >
                    🎯 {zone}
                  </span>
                ))}
              </div>
            </div>

            <div className="p-3.5 rounded-xl bg-white/5 text-xs text-gray-300 leading-relaxed border border-white/5">
              <strong className="text-white">Synthèse du Coach :</strong> {plan.analysis.coachSummary}
            </div>
          </div>
        </div>

        {/* Right: Predicted 8-Week Progression Chart */}
        <div className="lg:col-span-6 bg-[#16161E] border border-white/10 rounded-3xl p-6 space-y-4 shadow-xl flex flex-col justify-between">
          <div className="flex items-center justify-between pb-2 border-b border-white/10">
            <span className="text-xs font-extrabold uppercase text-amber-400 tracking-wider flex items-center gap-1.5">
              <Flame className="w-4 h-4" /> Projection de Transformation (8 Semaines)
            </span>
            <span className="text-[10px] text-gray-400">Basé sur 4s/semaine</span>
          </div>

          <div className="h-56 w-full pt-2">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={progressChartData}>
                <XAxis dataKey="week" stroke="#888" fontSize={11} />
                <YAxis hide />
                <Tooltip
                  contentStyle={{ backgroundColor: "#121218", borderColor: "#333", borderRadius: "8px" }}
                  labelStyle={{ color: "#fff", fontWeight: "bold" }}
                />
                <Line
                  type="monotone"
                  dataKey="muscleIdx"
                  name="Développement Musculaire"
                  stroke="#FF5500"
                  strokeWidth={3}
                  dot={{ fill: "#FF5500", r: 4 }}
                />
                <Line
                  type="monotone"
                  dataKey="fatIdx"
                  name="Taux de Masse Grasse %"
                  stroke="#10B981"
                  strokeWidth={2}
                  strokeDasharray="4 4"
                />
              </LineChart>
            </ResponsiveContainer>
          </div>

          <div className="flex items-center justify-between text-xs text-gray-300 pt-2 border-t border-white/10">
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded-full bg-[#FF5500]" />
              <span>Gain de Densité Musculaire</span>
            </div>
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded-full bg-emerald-500" />
              <span>Réduction de Masse Grasse</span>
            </div>
          </div>
        </div>
      </div>

      {/* 8-Week Progressive Overload Roadmap */}
      {plan.weeksProgression && plan.weeksProgression.length > 0 && (
        <div className="bg-[#16161E] border border-white/10 rounded-3xl p-6 space-y-4 shadow-xl">
          <div className="flex items-center justify-between pb-2 border-b border-white/10">
            <span className="text-xs font-extrabold uppercase text-[#FF5500] tracking-wider flex items-center gap-1.5">
              <Award className="w-4 h-4" /> Périodisation & Surcharge Progressive (8 Semaines)
            </span>
            <span className="bg-emerald-500/20 text-emerald-300 text-[10px] font-bold px-2.5 py-0.5 rounded border border-emerald-500/30">
              {plan.totalWeeks || 8} Semaines de Progression
            </span>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {plan.weeksProgression.map((wp) => (
              <div
                key={wp.weekNumber}
                className="bg-[#121218] border border-white/10 rounded-2xl p-4 space-y-2 hover:border-[#FF5500]/50 transition-colors"
              >
                <div className="flex items-center justify-between text-xs font-black text-[#FF5500]">
                  <span>BLOC {wp.weekNumber}</span>
                  <span className="text-[10px] text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
                    {wp.repsModifier}
                  </span>
                </div>
                <h4 className="font-extrabold text-xs text-white leading-snug">{wp.title}</h4>
                <p className="text-[11px] text-gray-400 leading-relaxed">{wp.focus}</p>
                <p className="text-[10px] text-amber-300 font-medium bg-white/5 p-2 rounded-lg">
                  💡 {wp.loadAdvice}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Week 1 Teaser Schedule (Exercises Blurred/Locked) */}
      <div className="bg-[#16161E] border border-white/10 rounded-3xl p-6 sm:p-8 space-y-6 shadow-xl relative overflow-hidden">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-white/10">
          <div>
            <h3 className="text-xl font-extrabold uppercase text-white font-display">
              Aperçu de la Semaine 1 ({plan.weekSchedule.length} Séances)
            </h3>
            <p className="text-xs text-gray-400">
              Style de Musique : <strong className="text-white">{plan.playlist.genre}</strong>
            </p>
          </div>
          <span className="bg-[#FF5500]/20 text-[#FF5500] border border-[#FF5500]/40 text-xs font-bold px-3 py-1 rounded-full flex items-center gap-1">
            <Music className="w-3.5 h-3.5" /> Playlist Workout Inclus
          </span>
        </div>

        {/* Days List */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {plan.weekSchedule.map((day) => (
            <div
              key={day.dayNumber}
              className="bg-[#121218] border border-white/10 rounded-2xl p-4 space-y-3 relative group"
            >
              <div className="flex items-center justify-between text-xs">
                <span className="font-black text-[#FF5500] uppercase">{day.dayName}</span>
                <span className="text-gray-400">{day.estimatedDurationMin} min</span>
              </div>
              <h4 className="font-bold text-sm text-white line-clamp-1">{day.title}</h4>

              {/* Blurred / Locked Exercises Preview */}
              <div className="space-y-1.5 pt-2 relative">
                <div className="text-[11px] text-gray-400 space-y-1 filter blur-[3px] select-none">
                  <p>• Développé couché — 4 x 8-10 reps</p>
                  <p>• Développé incliné — 4 x 10-12 reps</p>
                  <p>• Élévations latérales — 4 x 15 reps</p>
                  <p>• Extensions triceps — 3 x 12 reps</p>
                </div>

                {/* Lock Overlay */}
                <div className="absolute inset-0 flex items-center justify-center bg-black/40 backdrop-blur-[2px] rounded-lg border border-white/10">
                  <div className="flex items-center gap-1.5 bg-[#FF5500] text-white text-[11px] font-extrabold px-2.5 py-1 rounded-full shadow-lg">
                    <Lock className="w-3 h-3" />
                    <span>DÉBLOQUER DÉTAILS</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Primary Call To Action to Open Paywall */}
        <div className="pt-6 text-center space-y-4 border-t border-white/10">
          <div className="inline-flex items-center gap-2 text-xs text-amber-300 bg-amber-950/40 border border-amber-500/30 px-4 py-1.5 rounded-full">
            <Award className="w-4 h-4 text-amber-400" />
            <span>Débloquez l'accès complet aux exercices, conseils d'exécution, au Coach IA et aux musiques</span>
          </div>

          <div>
            <button
              onClick={onUnlockClick}
              className="w-full sm:w-auto bg-gradient-to-r from-[#FF5500] to-[#FF3E00] hover:from-[#FF6611] hover:to-[#FF4411] text-white font-black px-10 py-4 rounded-2xl text-lg shadow-2xl shadow-[#FF5500]/40 hover:scale-105 transition-all inline-flex items-center justify-center gap-3 cursor-pointer"
            >
              <Lock className="w-5 h-5 text-white" />
              <span>DÉBLOQUER MON PLAN D'ENTRAÎNEMENT COMPLET</span>
              <ArrowRight className="w-5 h-5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
