import React, { useState, useEffect, useRef } from "react";
import { WorkoutDay, ExerciseItem } from "../types";
import { StickFigureWarmup } from "./StickFigureWarmup";
import { PremiumExerciseIllustrationV2 } from "./PremiumExerciseIllustrationV2";
import { X, Play, Pause, SkipForward, SkipBack, Volume2, VolumeX, Plus, Minus, CheckCircle2, Award, Dumbbell, Timer } from "lucide-react";
import { Language, UI_LABELS, translateExerciseName, translateMuscleGroup } from "../utils/translator";
import { speakText, stopSpeech } from "../utils/speechUtils";

interface GuidedWorkoutPlayerProps { workoutDay: WorkoutDay; initialExerciseIdx?: number; language: Language; onClose: () => void; onWorkoutCompleted: () => void; onCheckEquipment?: (exercise: ExerciseItem) => void; }
type WorkoutPhase = "WARMUP" | "EXERCISE" | "REST" | "COMPLETE";
interface WarmupStep { name: string; durationSec: number; description: string; stickFigureMove: "shoulders" | "jacks" | "chest"; }
const WARMUP_STEPS: WarmupStep[] = [
  { name: "Rotations Épaules & Coudes", durationSec: 30, description: "Fais tourner tes épaules vers l'avant puis vers l'arrière, bras détendus. Enchaîne avec des rotations de coudes pour lubrifier les articulations.", stickFigureMove: "shoulders" },
  { name: "Jumping Jacks", durationSec: 30, description: "Sauts écartés bras/jambes pour élever ton rythme cardiaque et préparer tout le corps à l'effort.", stickFigureMove: "jacks" },
  { name: "Ouverture de Cage Thoracique", durationSec: 30, description: "Étirement dynamique de la poitrine et du haut du dos : bras écartés, ouvre et ferme la cage thoracique en respirant profondément.", stickFigureMove: "chest" }
];

export const GuidedWorkoutPlayer: React.FC<GuidedWorkoutPlayerProps> = ({ workoutDay, initialExerciseIdx = 0, language, onClose, onWorkoutCompleted, onCheckEquipment }) => {
  const t = UI_LABELS[language]; const exercises = workoutDay.exercises || [];
  const [phase, setPhase] = useState<WorkoutPhase>("WARMUP"); const [currentExIdx, setCurrentExIdx] = useState(initialExerciseIdx); const [currentSet, setCurrentSet] = useState(1); const [currentWarmupIdx, setCurrentWarmupIdx] = useState(0);
  const [timeLeft, setTimeLeft] = useState(WARMUP_STEPS[0].durationSec); const [isRunning, setIsRunning] = useState(true); const [isMuted, setIsMuted] = useState(false); const [isVoiceActive, setIsVoiceActive] = useState(false);
  interface CoachQueueItem { text: string; isEquipmentCheck?: boolean; }
  const [coachMessage, setCoachMessage] = useState<string | null>(null); const coachQueueRef = useRef<CoachQueueItem[]>([]); const coachTimeoutRef = useRef<number | null>(null); const firedCoachEventsRef = useRef<Set<string>>(new Set()); const [isCoachSpeaking, setIsCoachSpeaking] = useState(false); const [countdownValue, setCountdownValue] = useState<number | null>(null); const [awaitingEquipmentConfirm, setAwaitingEquipmentConfirm] = useState(false);

  const playBeep = (freq = 800, duration = 0.15) => { if (isMuted) return; try { const audioCtx = new (window.AudioContext || (window as any).webkitAudioContext)(); const osc = audioCtx.createOscillator(); const gain = audioCtx.createGain(); osc.type = "sine"; osc.frequency.value = freq; gain.gain.setValueAtTime(0.2, audioCtx.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + duration); osc.connect(gain); gain.connect(audioCtx.destination); osc.start(); osc.stop(audioCtx.currentTime + duration); } catch {} };
  const currentExercise: ExerciseItem | undefined = exercises[currentExIdx];

  const runPreStartCountdown = () => { setCountdownValue(3); playBeep(500, 0.12); let n = 3; const step = () => { n -= 1; if (n > 0) { setCountdownValue(n); playBeep(500, 0.12); window.setTimeout(step, 700); } else { playBeep(900, 0.2); setCountdownValue(null); } }; window.setTimeout(step, 700); };
  const handleAfterCoachSpeech = (wasEquipmentCheck: boolean) => { if (coachQueueRef.current.length > 0) { showNextCoachMessage(); return; } setIsCoachSpeaking(false); if (wasEquipmentCheck) setAwaitingEquipmentConfirm(true); else { setCoachMessage(null); runPreStartCountdown(); } };
  const showNextCoachMessage = () => { const next = coachQueueRef.current.shift(); if (!next) { setCoachMessage(null); setIsCoachSpeaking(false); runPreStartCountdown(); return; } setCoachMessage(next.text); setIsCoachSpeaking(true); const isLast = coachQueueRef.current.length === 0; const spoke = speakText(next.text, () => setIsCoachSpeaking(true), () => handleAfterCoachSpeech(!!next.isEquipmentCheck && isLast), () => window.setTimeout(() => handleAfterCoachSpeech(!!next.isEquipmentCheck && isLast), 3000)); if (!spoke) window.setTimeout(() => handleAfterCoachSpeech(!!next.isEquipmentCheck && isLast), 3200); };
  const triggerCoachMessage = (text: string, eventKey?: string, isEquipmentCheck?: boolean) => { if (eventKey) { if (firedCoachEventsRef.current.has(eventKey)) return; firedCoachEventsRef.current.add(eventKey); } coachQueueRef.current.push({ text, isEquipmentCheck }); if (!isCoachSpeaking && coachMessage === null && countdownValue === null && !awaitingEquipmentConfirm) showNextCoachMessage(); };
  const handleEquipmentConfirmYes = () => { setAwaitingEquipmentConfirm(false); setCoachMessage(null); runPreStartCountdown(); };
  const handleEquipmentConfirmNo = () => { setAwaitingEquipmentConfirm(false); setCoachMessage(null); if (onCheckEquipment && currentExercise) onCheckEquipment(currentExercise); runPreStartCountdown(); };

  useEffect(() => { triggerCoachMessage("C'est parti ! On commence en douceur avec l'échauffement, respire bien et prépare ton corps.", "intro"); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, []);
  useEffect(() => { if (phase === "EXERCISE" && currentSet === 1) triggerCoachMessage(`Prochain mouvement : ${exercises[currentExIdx]?.name || "cet exercice"}. As-tu tout le matériel nécessaire ?`, `equipment-check-${currentExIdx}`, true); if (phase === "EXERCISE" && currentExIdx === 0 && currentSet === 1) triggerCoachMessage("Premier exercice ! Concentre-toi sur la technique avant la charge.", "first-exercise"); if (phase === "EXERCISE" && exercises.length > 2 && currentExIdx === Math.floor(exercises.length / 2)) triggerCoachMessage("Tu es à la moitié de ta séance, garde ce rythme, c'est du solide.", "midpoint"); if (phase === "EXERCISE" && currentExIdx === exercises.length - 1) triggerCoachMessage("Dernier exercice de la séance, donne tout ce qu'il te reste !", "last-exercise"); if (phase === "REST" && currentExIdx === exercises.length - 1) triggerCoachMessage("Récupère bien, respire profondément, la séance touche à sa fin.", "final-rest"); if (phase === "COMPLETE") triggerCoachMessage("Séance forgée avec succès ! Ton corps te remerciera demain.", "complete"); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [phase, currentExIdx]);
  useEffect(() => () => { if (coachTimeoutRef.current) window.clearTimeout(coachTimeoutRef.current); }, []);

  const estimateExerciseDurationSec = (repsLabel?: string): number => { if (!repsLabel) return 45; const lower = repsLabel.toLowerCase(); const secMatch = lower.match(/(\d+)\s*sec/); if (secMatch) return Math.max(10, parseInt(secMatch[1], 10)); const minMatch = lower.match(/(\d+)\s*min/); if (minMatch) return Math.max(10, parseInt(minMatch[1], 10) * 60); const repsMatch = lower.match(/(\d+)/); if (repsMatch) return Math.min(90, Math.max(15, Math.round(parseInt(repsMatch[1], 10) * 2.3))); return 45; };
  const setupPhaseTimer = (newPhase: WorkoutPhase, exIdx: number, _setNum: number, warmupIdx = 0) => { if (newPhase === "WARMUP") setTimeLeft(WARMUP_STEPS[warmupIdx]?.durationSec || 30); else if (newPhase === "EXERCISE") setTimeLeft(estimateExerciseDurationSec(exercises[exIdx]?.reps)); else if (newPhase === "REST") setTimeLeft(exercises[exIdx]?.restSeconds || 45); };

  const handleAutoAdvancePhase = () => { stopSpeech(); if (phase === "WARMUP") { if (currentWarmupIdx < WARMUP_STEPS.length - 1) { const next = currentWarmupIdx + 1; setCurrentWarmupIdx(next); setupPhaseTimer("WARMUP", 0, 1, next); } else { setPhase("EXERCISE"); setCurrentExIdx(0); setCurrentSet(1); setupPhaseTimer("EXERCISE", 0, 1); } } else if (phase === "EXERCISE") { setPhase("REST"); setupPhaseTimer("REST", currentExIdx, currentSet); } else if (phase === "REST") { const ex = exercises[currentExIdx]; const totalSets = ex?.sets || 3; if (currentSet < totalSets) { const nextSet = currentSet + 1; setCurrentSet(nextSet); setPhase("EXERCISE"); setupPhaseTimer("EXERCISE", currentExIdx, nextSet); } else if (currentExIdx < exercises.length - 1) { const nextExIdx = currentExIdx + 1; setCurrentExIdx(nextExIdx); setCurrentSet(1); setPhase("EXERCISE"); setupPhaseTimer("EXERCISE", nextExIdx, 1); } else { setPhase("COMPLETE"); setIsRunning(false); playBeep(1000, 0.5); } } };
  const handleSkipNext = () => handleAutoAdvancePhase();
  const handleGoPrevious = () => { stopSpeech(); if (phase === "REST") { setPhase("EXERCISE"); setupPhaseTimer("EXERCISE", currentExIdx, currentSet); } else if (phase === "EXERCISE") { if (currentSet > 1) { const s = currentSet - 1; setCurrentSet(s); setupPhaseTimer("EXERCISE", currentExIdx, s); } else if (currentExIdx > 0) { const prevExIdx = currentExIdx - 1; const prevEx = exercises[prevExIdx]; setCurrentExIdx(prevExIdx); setCurrentSet(prevEx?.sets || 3); setPhase("EXERCISE"); setupPhaseTimer("EXERCISE", prevExIdx, prevEx?.sets || 3); } else { setPhase("WARMUP"); setCurrentWarmupIdx(WARMUP_STEPS.length - 1); setupPhaseTimer("WARMUP", 0, 1, WARMUP_STEPS.length - 1); } } else if (phase === "WARMUP" && currentWarmupIdx > 0) { const prevWarmupIdx = currentWarmupIdx - 1; setCurrentWarmupIdx(prevWarmupIdx); setupPhaseTimer("WARMUP", 0, 1, prevWarmupIdx); } };

  useEffect(() => { if (!isRunning || timeLeft <= 0 || phase === "COMPLETE" || isCoachSpeaking || countdownValue !== null || awaitingEquipmentConfirm) { if (isRunning && timeLeft === 0 && phase !== "COMPLETE" && !isCoachSpeaking && countdownValue === null && !awaitingEquipmentConfirm) handleAutoAdvancePhase(); return; } const interval = window.setInterval(() => { setTimeLeft((prev) => { if (prev <= 1) { playBeep(1200, 0.3); return 0; } if (prev <= 4) playBeep(600, 0.1); return prev - 1; }); }, 1000); return () => window.clearInterval(interval); }, [isRunning, timeLeft, phase, isCoachSpeaking, countdownValue, awaitingEquipmentConfirm]);

  const handleAdjustTime = (deltaSeconds: number) => { setTimeLeft((prev) => Math.min(599, Math.max(0, prev + deltaSeconds))); };
  const handleToggleVoice = () => { if (isVoiceActive) { stopSpeech(); setIsVoiceActive(false); } else if (currentExercise && phase === "EXERCISE") { const textToSpeak = `${translateExerciseName(currentExercise.name, language)}. ${t.sets}: ${currentSet} sur ${currentExercise.sets}. À faire : ${currentExercise.reps}. ${currentExercise.tips}`; setIsVoiceActive(true); speakText(textToSpeak, () => setIsVoiceActive(true), () => setIsVoiceActive(false), () => setIsVoiceActive(false)); } };
  const formatTime = (secs: number) => `${Math.floor(secs / 60)}:${(secs % 60).toString().padStart(2, "0")}`;
  const totalStepsInWorkout = exercises.length * 2 + 1; const completedSteps = phase === "WARMUP" ? 0 : currentExIdx * 2 + (phase === "REST" ? 2 : 1); const progressPercent = Math.min(100, Math.round((completedSteps / totalStepsInWorkout) * 100));

  return (
    <div className="fixed inset-0 z-50 bg-[#0A0A0E] text-white flex flex-col h-screen overflow-hidden select-none animate-in fade-in zoom-in-95">
      {coachMessage && <div className="absolute top-4 left-1/2 -translate-x-1/2 z-[60] max-w-md w-[92%] animate-in slide-in-from-top-4 fade-in duration-300"><div className="bg-gradient-to-r from-[#FF5500] to-[#FF8A00] rounded-2xl px-4 py-3 shadow-2xl shadow-[#FF5500]/30"><div className="flex items-start gap-3"><div className="w-8 h-8 rounded-full bg-black/20 flex items-center justify-center shrink-0 mt-0.5"><span className={`text-sm ${isCoachSpeaking ? "animate-pulse" : ""}`}>🤖</span></div><div className="flex-1 min-w-0"><p className="text-[10px] font-black uppercase tracking-wider text-black/70 mb-0.5">Coach IA FysiqForge {isCoachSpeaking && "· en train de parler..."}</p><p className="text-sm font-bold text-black leading-snug">{coachMessage}</p></div></div>{awaitingEquipmentConfirm && <div className="flex gap-2 mt-3"><button onClick={handleEquipmentConfirmYes} className="flex-1 bg-black text-white font-bold text-xs py-2.5 rounded-xl">✅ J'ai tout, c'est bon</button><button onClick={handleEquipmentConfirmNo} className="flex-1 bg-white text-black font-bold text-xs py-2.5 rounded-xl">❌ Il me manque un truc</button></div>}</div></div>}
      {countdownValue !== null && <div className="absolute inset-0 z-[70] bg-black/80 backdrop-blur-sm flex flex-col items-center justify-center gap-4"><p className="text-sm font-bold uppercase tracking-widest text-[#FF8A3D]">C'est parti dans</p><div key={countdownValue} className="text-[120px] font-black text-white leading-none">{countdownValue}</div></div>}
      <header className="bg-[#121218]/90 border-b border-white/10 px-4 py-3 flex items-center justify-between shrink-0"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-xl bg-[#FF5500] flex items-center justify-center font-bold text-white"><Dumbbell className="w-5 h-5" /></div><div><div className="flex items-center gap-2"><span className="text-xs font-black text-[#FF5500] uppercase tracking-wider">{workoutDay.dayName} — {t.startWorkout}</span><span className="bg-emerald-500/20 text-emerald-400 text-[10px] font-extrabold px-2 py-0.5 rounded border border-emerald-500/30">AUTO-CHRONO ACTIVE</span></div><h2 className="text-sm sm:text-base font-extrabold uppercase truncate max-w-[280px] sm:max-w-md">{workoutDay.title}</h2></div></div><div className="flex items-center gap-2"><button onClick={() => setIsMuted(!isMuted)} className={`p-2 rounded-xl text-xs font-bold border ${isMuted ? "bg-red-500/20 text-red-400 border-red-500/30" : "bg-white/5 text-gray-300 border-white/10"}`}>{isMuted ? <VolumeX className="w-4 h-4" /> : <Volume2 className="w-4 h-4 text-[#FF5500]" />}</button><button onClick={() => { stopSpeech(); onClose(); }} className="p-2 bg-white/10 rounded-xl"><X className="w-5 h-5" /></button></div></header>
      <div className="w-full bg-white/5 h-1.5 shrink-0"><div className="bg-gradient-to-r from-[#FF5500] to-emerald-400 h-full transition-all duration-500" style={{ width: `${progressPercent}%` }} /></div>
      <main className="flex-1 flex flex-col lg:flex-row items-center justify-center p-4 sm:p-6 gap-6 overflow-y-auto">
        <div className="w-full lg:w-1/2 max-w-xl flex flex-col items-center text-center space-y-4">
          <div className="flex items-center gap-2">{phase === "WARMUP" && <span className="bg-amber-500/20 text-amber-300 border border-amber-500/30 text-xs font-black px-3.5 py-1.5 rounded-full uppercase">🔥 {t.warmupPhase}</span>}{phase === "EXERCISE" && <span className="bg-[#FF5500]/20 text-[#FF5500] border border-[#FF5500]/30 text-xs font-black px-3.5 py-1.5 rounded-full uppercase"><Dumbbell className="w-4 h-4 inline" /> {t.exercisePhase} — EXERCICE {currentExIdx + 1} / {exercises.length}</span>}{phase === "REST" && <span className="bg-blue-500/20 text-blue-300 border border-blue-500/30 text-xs font-black px-3.5 py-1.5 rounded-full uppercase"><Timer className="w-4 h-4 inline" /> {t.restPhase}</span>}{phase === "COMPLETE" && <span className="bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 text-xs font-black px-3.5 py-1.5 rounded-full uppercase"><Award className="w-4 h-4 inline" /> {t.workoutComplete}</span>}</div>
          <div key={`img-${phase}-${currentExIdx}-${currentSet}`} className="relative w-full h-64 sm:h-80 rounded-3xl overflow-hidden border-2 border-white/10 shadow-2xl bg-black group animate-fade-slide">{phase === "WARMUP" ? <StickFigureWarmup key={`stick-${currentWarmupIdx}`} move={WARMUP_STEPS[currentWarmupIdx]?.stickFigureMove || "shoulders"} /> : phase === "REST" ? <div className="w-full h-full flex items-center justify-center bg-[#1A120C]"><span className="text-6xl animate-pulse">😮‍💨</span></div> : <PremiumExerciseIllustrationV2 key={`premium-${currentExIdx}-${currentSet}`} exerciseId={currentExercise?.id} exerciseName={currentExercise?.name} muscleGroup={currentExercise?.muscleGroup} />}
            <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-transparent pointer-events-none" />
            {phase !== "COMPLETE" && <div className="absolute bottom-4 left-4 right-4 flex items-center justify-between"><div className="bg-black/80 backdrop-blur-md border border-white/20 px-4 py-2 rounded-2xl flex items-center gap-3"><div className="w-3 h-3 rounded-full bg-[#FF5500]" /><span className="font-mono text-3xl sm:text-4xl font-black tracking-widest text-white">{formatTime(timeLeft)}</span></div>{phase === "EXERCISE" && currentExercise && <div className="bg-[#FF5500] text-white px-3.5 py-2 rounded-2xl font-black text-xs sm:text-sm shadow-xl">{t.sets} {currentSet} / {currentExercise.sets}</div>}</div>}
          </div>
          <div className="flex items-center gap-3 pt-2"><button aria-label="Retirer 15 secondes" onClick={() => handleAdjustTime(-15)} className="px-3 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-xs font-bold text-gray-300 flex items-center gap-1 cursor-pointer"><Minus className="w-3.5 h-3.5" /> 15s</button><button onClick={() => setIsRunning(!isRunning)} className={`px-6 py-3 rounded-2xl font-black text-sm flex items-center gap-2 shadow-xl cursor-pointer ${isRunning ? "bg-amber-500 text-black" : "bg-[#FF5500] text-white"}`}>{isRunning ? <Pause className="w-5 h-5 fill-current" /> : <Play className="w-5 h-5 fill-current" />}<span>{isRunning ? t.pause : t.resume}</span></button><button aria-label="Ajouter 15 secondes" onClick={() => handleAdjustTime(15)} className="px-3 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-xs font-bold text-gray-300 flex items-center gap-1 cursor-pointer"><Plus className="w-3.5 h-3.5" /> 15s</button></div>
        </div>
        <div key={`panel-${phase}-${currentExIdx}-${currentSet}`} className="w-full lg:w-1/2 max-w-xl bg-[#16161E] border border-white/10 rounded-3xl p-6 space-y-5 shadow-2xl">
          {phase === "WARMUP" && <div className="space-y-4"><div><span className="text-xs font-bold text-amber-400 uppercase tracking-wider">Échauffement — Mouvement {currentWarmupIdx + 1} sur {WARMUP_STEPS.length}</span><h3 className="text-2xl font-black uppercase text-white font-display">{WARMUP_STEPS[currentWarmupIdx]?.name}</h3></div><p className="text-sm text-gray-300 leading-relaxed bg-[#121218] p-4 rounded-2xl border border-white/5">{WARMUP_STEPS[currentWarmupIdx]?.description}</p><div className="flex items-center gap-2">{WARMUP_STEPS.map((step, idx) => <div key={step.name} className={`flex-1 h-1.5 rounded-full ${idx < currentWarmupIdx ? "bg-amber-500" : idx === currentWarmupIdx ? "bg-amber-400" : "bg-white/10"}`} />)}</div></div>}
          {phase === "EXERCISE" && currentExercise && <div className="space-y-4"><div><span className="text-xs font-bold text-[#FF5500] uppercase">Exercice {currentExIdx + 1} sur {exercises.length}</span><h3 className="text-2xl font-black uppercase text-white font-display">{translateExerciseName(currentExercise.name, language)}</h3><p className="text-xs text-gray-400 mt-1">{translateMuscleGroup(currentExercise.muscleGroup, language)}</p></div><div className="grid grid-cols-3 gap-3"><div className="bg-[#121218] p-3 rounded-xl border border-white/5"><p className="text-[10px] text-gray-500 uppercase">Séries</p><p className="text-lg font-black">{currentExercise.sets}</p></div><div className="bg-[#121218] p-3 rounded-xl border border-white/5"><p className="text-[10px] text-gray-500 uppercase">À faire</p><p className="text-lg font-black text-[#FF8A3D]">{currentExercise.reps}</p></div><div className="bg-[#121218] p-3 rounded-xl border border-white/5"><p className="text-[10px] text-gray-500 uppercase">Maintenant</p><p className="text-lg font-black">Série {currentSet}/{currentExercise.sets}</p></div></div><div className="bg-[#121218] p-4 rounded-2xl border border-[#FF5500]/20"><p className="text-[10px] font-black text-[#FF5500] uppercase mb-1">🎯 Ce que tu fais maintenant</p><p className="text-sm font-bold text-white">Fais <span className="text-[#FF8A3D]">{currentExercise.reps}</span>, puis arrête-toi. Le chrono est seulement un repère de temps.</p></div><div className="bg-[#121218] p-4 rounded-2xl border border-white/5"><p className="text-[10px] font-black text-[#FF5500] uppercase mb-1">Comment faire</p><p className="text-xs text-gray-300 leading-relaxed">{currentExercise.tips}</p></div><button onClick={handleToggleVoice} className="w-full bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl py-2.5 text-xs font-bold">{isVoiceActive ? "🔊 Arrêter le coach vocal" : "🔊 Écouter les instructions"}</button></div>}
          {phase === "REST" && <div className="space-y-4 text-center"><span className="text-xs font-bold text-blue-400 uppercase">Récupération</span><h3 className="text-2xl font-black uppercase">Respire et récupère</h3><p className="text-sm text-gray-400">Prépare-toi pour la prochaine série ou le prochain exercice.</p></div>}
          {phase === "COMPLETE" && <div className="space-y-5 text-center"><div className="w-16 h-16 mx-auto rounded-full bg-emerald-500/20 flex items-center justify-center"><CheckCircle2 className="w-8 h-8 text-emerald-400" /></div><h3 className="text-2xl font-black uppercase">Séance terminée</h3><p className="text-sm text-gray-400">Excellent travail. Ton bilan peut maintenant être enregistré.</p><button onClick={() => { onWorkoutCompleted(); onClose(); }} className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-black py-4 rounded-2xl text-xs uppercase tracking-wider">Enregistrer le bilan ✓</button></div>}
          {phase !== "COMPLETE" && <div className="flex items-center justify-between pt-4 border-t border-white/10"><button onClick={handleGoPrevious} className="px-4 py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 text-gray-300 rounded-xl text-xs font-bold flex items-center gap-1.5"><SkipBack className="w-4 h-4" />{t.previous}</button><button onClick={handleSkipNext} className="px-5 py-2.5 bg-[#FF5500] hover:bg-[#FF6611] text-white rounded-xl text-xs font-black flex items-center gap-1.5"><span>{t.skip}</span><SkipForward className="w-4 h-4" /></button></div>}
        </div>
      </main>
    </div>
  );
};
